version: '3.9'

services:
  
  gamers-dir:
    build: .
    networks:
    - gamers
    expose:
    - 8080
    ports:
    - "8080:8080"    
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gamers      
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgres      

  postgres:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gamers
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - gamers

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "8888:8080"
    networks:
      - gamers

volumes:
  postgresdata:

networks:
  gamers: